dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "pawelworwa-github"
    token:
      secure: "89a5ecb69279328a0c52f2ec9d3416b2a53c65aa"
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles"
  - make clean
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'